# See the documentation for more information:
# https://packit.dev/docs/configuration/

specfile_path: rpm/deepin-network-utils.spec

# add or remove files that should be synced
synced_files:
    - rpm/deepin-network-utils.spec
    - .packit.yaml

upstream_package_name: dde-network-utils
# downstream (Fedora) RPM package name
downstream_package_name: deepin-network-utils

actions:
  fix-spec-file: |
    bash -c "sed -i -r \"s/Version:(\s*)\S*/Version:\1${PACKIT_PROJECT_VERSION}/\" rpm/deepin-network-utils.spec"
